### ISSUE TITLE
unit test broken in ux/navigation branch

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach#662]
```  
20 passing (27s)
  1 failing

  1) Reports endpoint
       Update an report (POST /reports):
     Uncaught AssertionError: expected 200 "OK", got 404 "Not Found" {"req":{"method":"post","url":"http://127.0.0.1:49707/api/reports/1","data":{"status":"confirmed","content":{"updated_by":"integrated tester"}}},"header":{"x-powered-by":"Express","surrogate-control":"no-store","cache-control":"no-store, no-cache, must-revalidate, proxy-revalidate","pragma":"no-cache","expires":"0","content-type":"application/json; charset=utf-8","content-length":"46","etag":"W/\"2e-LpArEc9NI9u5QT+RZekPgmdz0f4\"","date":"Sat, 20 Oct 2018 01:15:13 GMT","connection":"close"},"status":404,"text":"{\"message\":\"URL not found\",\"url\":\"/reports/1\"}"}
      at UnitJS.fail (node_modules/unit.js/src/helpers.js:204:5)
      at /Users/matthew/code/msf-reach/src/test/testMSFREACHServer.js:388:38
      at Test.assert (node_modules/supertest/lib/test.js:205:12)
      at Server.assert (node_modules/supertest/lib/test.js:132:12)
      at Object.apply (node_modules/harmony-reflect/reflect.js:2064:37)
      at Object.apply (node_modules/harmony-reflect/reflect.js:2064:37)
      at Object.apply (node_modules/harmony-reflect/reflect.js:2064:37)
      at Server.EventEmitter.emit (domain.js:442:20)
      at emitCloseNT (net.js:1618:8)
      at Object.apply (node_modules/harmony-reflect/reflect.js:2064:37)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

(note that deployment won't occur while unit tests are broken)

**Comment by qclin** [comment]
Ah good, because it’s an update so I change endpoint to PUT. Can update unit text soon
